/**
 * Domain configuration for {{SERVICE_DISPLAY_NAME}}
 * Generated by Clodo Framework
 */

export const domains = {
  // Primary domain for this service
  primary: '{{DOMAIN_NAME}}',

  // Alternative domains (add as needed)
  alternatives: [
    // 'www.{{DOMAIN_NAME}}',
    // 'staging.{{DOMAIN_NAME}}'
  ],

  // NOTE: This directory is a sample config file for template authors. It is intentionally
  // named `config.example` now to avoid being accidentally copied into generated services.

  // Environment-specific domain mappings
  environments: {
    development: '{{SERVICE_NAME}}-dev.{{WORKERS_DEV_DOMAIN}}',
    staging: 'staging.{{DOMAIN_NAME}}',
    production: '{{DOMAIN_NAME}}'
  },

  // Routing configuration
  routing: {
    // SPA fallback - serve index.html for client-side routing
    spaFallback: true,
    spaFallbackPath: '/index.html',

    // Clean URLs - serve .html files without extension
    cleanUrls: true,

    // Trailing slash handling
    trailingSlash: false
  }
};