import { BaseGenerator } from '../BaseGenerator.js';
import { join } from 'path';
import { mkdirSync, writeFileSync } from 'fs';

/**
 * Service Middleware Generator (v4.4.1+)
 * 
 * IMPORTANT: As of v4.4.1, middleware is imported directly from @tamyla/clodo-framework.
 * This generator now creates a thin middleware config file instead of duplicating
 * framework functionality with MiddlewareRegistry/MiddlewareComposer/Shared.*.
 * 
 * The generated worker (WorkerIndexGenerator) imports:
 *   createCorsMiddleware, createErrorHandler, createLogger, createRateLimitGuard,
 *   composeMiddleware, createBearerAuth, createApiKeyAuth
 * directly from the framework.
 * 
 * This generator only creates:
 *   src/middleware/config.js — service-specific middleware configuration
 */
export class ServiceMiddlewareGenerator extends BaseGenerator {
  /**
   * Generate service middleware configuration
   * @param {Object} context - Generation context
   * @returns {Promise<string>} Path to generated middleware config file
   */
  async generate(context) {
    const { coreInputs, confirmedValues, servicePath } = this.extractContext(context);
    
    if (!this.shouldGenerate(context)) {
      return null;
    }

    const rawFeatures = confirmedValues.features || {};
    const features = Array.isArray(rawFeatures)
      ? Object.fromEntries(rawFeatures.map(f => [f, true]))
      : rawFeatures;

    // Generate a clean middleware config that re-uses framework APIs
    const configContent = `/**
 * ${confirmedValues.displayName} - Middleware Configuration
 *
 * Generated by Clodo Framework v4.4.1
 * Service Type: ${coreInputs.serviceType}
 *
 * This file configures the middleware stack for your service.
 * All middleware is imported from @tamyla/clodo-framework — no local
 * duplicates. Edit the options below to customize behavior.
 */

import {
  createCorsMiddleware,
  createErrorHandler,
  createLogger,${features.rateLimiting ? '\n  createRateLimitGuard,' : ''}${features.authentication ? '\n  createBearerAuth,' : ''}
  composeMiddleware
} from '@tamyla/clodo-framework';

/**
 * Middleware configuration for ${coreInputs.serviceName}
 * Modify these options to customize your middleware stack.
 */
export const middlewareConfig = {
  cors: {
    origins: ['*'],
    methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS'],
    headers: ['Content-Type', 'Authorization'],
    credentials: false
  },
  logger: {
    prefix: '${coreInputs.serviceName}',
    level: 'info',
    includeHeaders: false
  },
  errorHandler: {
    includeStack: false,
    logErrors: true
  }${features.rateLimiting ? `,
  rateLimit: {
    maxRequests: 100,
    windowMs: 60000
  }` : ''}${features.authentication ? `,
  auth: {
    // Configure your auth strategy:
    // token: env.SECRET_KEY  (for bearer auth)
    // keys: [env.API_KEY]    (for API key auth)
    realm: '${coreInputs.serviceName}'
  }` : ''}${(features.durableObject || features.durableObjects) ? `,
  // Durable Objects / DurableObject placeholder - update with your binding name
  // Example: DurableObject binding name -> DURABLE_OBJECT
  durable: {
    namespace: 'DURABLE_OBJECT'
  }` : ''}
};

/**
 * Create the composed middleware stack from configuration.
 * Called from the worker entry point.
 */
export function createMiddlewareStack(config = middlewareConfig) {
  return composeMiddleware(
    createCorsMiddleware(config.cors),
    createLogger(config.logger),${features.rateLimiting ? '\n    createRateLimitGuard(config.rateLimit),' : ''}
    createErrorHandler(config.errorHandler)
  );
}
`;

    // Ensure directory exists
    const dir = join(servicePath, 'src', 'middleware');
    mkdirSync(dir, { recursive: true });

    const filePath = join(servicePath, 'src', 'middleware', 'config.js');
    writeFileSync(filePath, configContent, 'utf8');
    this.logger.info(`Generated: ${filePath}`);

    return filePath;
  }

  /**
   * Determine if generator should run
   */
  shouldGenerate(context) {
    return true;
  }
}

