name = "{{SERVICE_NAME}}-staging"
main = "src/worker/index.js"
compatibility_date = "{{CURRENT_DATE}}"

[env.staging]
name = "{{SERVICE_NAME}}-staging"

[env.production]
name = "{{SERVICE_NAME}}-production"

# Database bindings will be added during deployment
# [[d1_databases]]
# binding = "{{SERVICE_NAME}}-db"
# database_name = "{{SERVICE_NAME}}-db"

# Environment variables
[vars]
DOMAIN_NAME = "{{SERVICE_NAME}}"
ENVIRONMENT = "development"
SERVICE_NAME = "{{SERVICE_NAME}}"
SERVICE_TYPE = "{{SERVICE_TYPE}}"

# Add your custom environment variables here
# CUSTOM_VAR = "value"