import { createDomainConfigSchema } from '@tamyla/clodo-framework';

/**
 * Domain configuration for Test Api Service
 *
 * Generated by Clodo Framework GenerationEngine
 * Service Type: api-service
 * Generated: 2026-02-04T03:49:23.564Z
 */

export const domains = {
  'test-api-service': {
    ...createDomainConfigSchema(),
    name: 'test-api-service',
    displayName: 'Test Api Service',
    description: 'A Clodo Framework service providing core functionality and extensibility',
    accountId: 'undefined',
    zoneId: 'undefined',
    domains: {
      production: 'https://test-api-service.test.example.com',
      staging: 'https://test-api-service-sta.test.example.com',
      development: 'https://test-api-service-dev.test.example.com'
    },
    services: [
      'test-api-service'
    ],
    databases: [
      {
        name: 'test-api-service-db',
        type: 'd1',
        binding: 'DB'
      }
    ],
    features: {
    "logging": true,
    "monitoring": true,
    "errorReporting": true,
    "metrics": true,
    "healthChecks": true,
    "extensibility": true,
    "configuration": true,
    "deployment": true,
    "d1": true
},
    metadata: {
      version: '1.0.0',
      author: 'Clodo Framework',
      generatedAt: '2026-02-04T03:49:23.564Z',
      frameworkVersion: '3.0.0',
      serviceType: 'api-service',
      environment: 'development'
    }
  }
};

export default domains;
