/**
 * Test Api Service - Cloudflare Worker
 *
 * Generated by Clodo Framework GenerationEngine
 * Service Type: api-service
 */

import { domains } from '../config/domains.js';
import { createServiceHandlers } from '../handlers/service-handlers.js';
import { MiddlewareRegistry, MiddlewareComposer } from '../middleware/runtime.js';
import * as Shared from '../middleware/shared/index.js';

export default {
  async fetch(request, env, ctx) {
    try {
      // Get service configuration
      const serviceConfig = domains['test-api-service'];

      // Build shared middleware instances
      const sharedMiddlewares = [
        Shared.cors({ origin: serviceConfig.corsPolicy || '*' }),
        Shared.logging({ level: serviceConfig.logLevel || 'info' })
      ];

      // Lazy-load service middleware and support legacy factory compatibility
      let serviceMiddlewareInstance = null;
      let legacyFactory = null;

      try {
        const mod = await import('../middleware/service-middleware.js');

        if (mod?.registerMiddleware) {
          // New-style registration helper
          mod.registerMiddleware(MiddlewareRegistry, serviceConfig.name);
          serviceMiddlewareInstance = MiddlewareRegistry.get(serviceConfig.name);
        } else if (mod?.default) {
          const def = mod.default;
          // If the default is a class (constructor), instantiate and register
          if (typeof def === 'function' && def.prototype) {
            try {
              const instance = new def();
              MiddlewareRegistry.register(serviceConfig.name, instance);
              serviceMiddlewareInstance = instance;
            } catch (e) {
              // ignore instantiation errors
            }
          } else if (typeof def === 'function') {
            // Legacy factory exported as default
            legacyFactory = def;
          }
        } else if (mod?.createServiceMiddleware) {
          legacyFactory = mod.createServiceMiddleware;
        }
      } catch (e) {
        // No service-specific middleware found - continue with shared only
      }

      // Compose final middleware chain
      let chain;

      if (legacyFactory) {
        const legacyInstance = legacyFactory(serviceConfig, env);
        const adapter = {
          preprocess: async (req) => {
            if (legacyInstance && typeof legacyInstance.processRequest === 'function') {
              const processed = await legacyInstance.processRequest(req);
              if (processed instanceof Response) return processed; // short-circuit
              return null; // continue (legacy returns a Request)
            }
            return null;
          },
          postprocess: async (res) => {
            if (legacyInstance && typeof legacyInstance.processResponse === 'function') {
              const r = await legacyInstance.processResponse(res);
              return r instanceof Response ? r : res;
            }
            return res;
          }
        };

        chain = MiddlewareComposer.compose(...sharedMiddlewares, adapter);
      } else {
        const svcMw = serviceMiddlewareInstance || MiddlewareRegistry.get(serviceConfig.name);
        chain = MiddlewareComposer.compose(...sharedMiddlewares, svcMw);
      }

      // Execute middleware chain with final handler
      const response = await chain.execute(request, async (req) => {
        const handlers = createServiceHandlers(serviceConfig, env);
        return handlers.handleRequest(req, ctx);
      });

      return response;

    } catch (error) {
      console.error('Worker error:', error);

      return new Response(JSON.stringify({
        error: 'Internal Server Error',
        message: error.message,
        timestamp: new Date().toISOString()
      }), {
        status: 500,
        headers: {
          'Content-Type': 'application/json',
          'X-Service': 'test-api-service',
          'X-Version': '1.0.0'
        }
      });
    }
  }
};
