# Deployment script for {{SERVICE_NAME}}
# Generated by Clodo Framework

param(
    [string]$Environment = "production",
    [switch]$DryRun,
    [switch]$Verbose
)

Write-Host "🚀 Deploying {{SERVICE_DISPLAY_NAME}} ($Environment)" -ForegroundColor Cyan
Write-Host "Generated by Clodo Framework" -ForegroundColor Gray
Write-Host ""

# Load environment variables
if (Test-Path ".env") {
    Write-Host "📋 Loading environment configuration..." -ForegroundColor Yellow
    Get-Content ".env" | ForEach-Object {
        if ($_ -match "^([^#][^=]+)=(.*)$") {
            $key = $matches[1].Trim()
            $value = $matches[2].Trim()
            [Environment]::SetEnvironmentVariable($key, $value)
        }
    }
} else {
    Write-Warning "⚠️  No .env file found. Using defaults."
}

# Validate required environment variables
$requiredVars = @("CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ACCOUNT_ID")
$missingVars = @()

foreach ($var in $requiredVars) {
    if (-not [Environment]::GetEnvironmentVariable($var)) {
        $missingVars += $var
    }
}

if ($missingVars.Count -gt 0) {
    Write-Error "❌ Missing required environment variables: $($missingVars -join ', ')"
    Write-Host "Please set these in your .env file or environment." -ForegroundColor Red
    exit 1
}

# Set deployment environment
$env:CLOUDFLARE_API_TOKEN = [Environment]::GetEnvironmentVariable("CLOUDFLARE_API_TOKEN")
$env:CLOUDFLARE_ACCOUNT_ID = [Environment]::GetEnvironmentVariable("CLOUDFLARE_ACCOUNT_ID")

if ($Verbose) {
    Write-Host "🔧 Environment: $Environment" -ForegroundColor Blue
    Write-Host "📦 Service: {{SERVICE_NAME}}" -ForegroundColor Blue
    Write-Host "🌐 Domain: {{DOMAIN_NAME}}" -ForegroundColor Blue
}

# Check if wrangler is available
try {
    $wranglerVersion = & wrangler --version 2>$null
    Write-Host "✅ Wrangler version: $wranglerVersion" -ForegroundColor Green
} catch {
    Write-Error "❌ Wrangler CLI not found. Please install: npm install -g wrangler"
    exit 1
}

# Validate static files exist
if (-not (Test-Path "public")) {
    Write-Error "❌ Public directory not found. Please ensure static files are in ./public/"
    exit 1
}

$fileCount = (Get-ChildItem "public" -Recurse -File).Count
Write-Host "📁 Found $fileCount static files in public directory" -ForegroundColor Blue

# Dry run mode
if ($DryRun) {
    Write-Host "🏃 Dry run mode - would execute:" -ForegroundColor Yellow
    Write-Host "   wrangler deploy --env $Environment" -ForegroundColor Gray
    Write-Host ""
    Write-Host "✅ Dry run complete - no changes made" -ForegroundColor Green
    exit 0
}

# Deploy to Cloudflare
Write-Host "🚀 Starting deployment..." -ForegroundColor Cyan

try {
    if ($Verbose) {
        & wrangler deploy --env $Environment
    } else {
        & wrangler deploy --env $Environment 2>$null
    }

    if ($LASTEXITCODE -eq 0) {
        Write-Host "" -ForegroundColor Green
        Write-Host "✅ Deployment successful!" -ForegroundColor Green
        Write-Host "🌐 Your site is now live at: https://{{DOMAIN_NAME}}" -ForegroundColor Cyan
        Write-Host ""

        # Health check
        Write-Host "🔍 Running health check..." -ForegroundColor Yellow
        try {
            $healthResponse = Invoke-WebRequest -Uri "https://{{DOMAIN_NAME}}/health" -TimeoutSec 10 -UseBasicParsing
            if ($healthResponse.StatusCode -eq 200) {
                Write-Host "✅ Health check passed" -ForegroundColor Green
            } else {
                Write-Warning "⚠️  Health check returned status: $($healthResponse.StatusCode)"
            }
        } catch {
            Write-Warning "⚠️  Health check failed: $($_.Exception.Message)"
        }

    } else {
        Write-Error "❌ Deployment failed with exit code: $LASTEXITCODE"
        exit $LASTEXITCODE
    }

} catch {
    Write-Error "❌ Deployment error: $($_.Exception.Message)"
    exit 1
}

Write-Host ""
Write-Host "🎉 {{SERVICE_DISPLAY_NAME}} deployment complete!" -ForegroundColor Green