import { createDomainConfigSchema } from '../../../src/index.js';

/**
 * Domain configuration for undefined
 *
 * Generated by Clodo Framework GenerationEngine
 * Service Type: generic
 * Generated: 2025-10-08T13:13:16.321Z
 */

export const domains = {
  'test': {
    ...createDomainConfigSchema(),
    name: 'test',
    displayName: 'undefined',
    description: 'test',
    accountId: 'acc',
    zoneId: 'zone',
    domains: {
      production: 'undefined',
      staging: 'undefined',
      development: 'undefined'
    },
    services: [
      'test'
    ],
    databases: [
      {
        name: 'undefined',
        type: 'd1',
        binding: 'DB'
      }
    ],
    features: {},
    metadata: {
      version: '1.0.0',
      author: 'test',
      generatedAt: '2025-10-08T13:13:16.321Z',
      frameworkVersion: '3.0.0',
      serviceType: 'generic',
      environment: 'dev'
    }
  }
};

export default domains;
